name: E2E Test Job

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: runs-on=${{ github.run_id }}/runner=2cpu-linux-x64/env=test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy script
        run: echo "Runs on RunsOn!"
